// === 第二关《洞川撤退》全新剧本：**全角色扩充版无线电台词（全程碎嘴互怼版）** ==========
//
// 用户要求（原话要点）:
//   · 完全替换旧台词, 语音仍是**占位符**(靠 voiceSpeaker, 复用现有 6 个占位音色);
//   · 照搬第一关的播放机制(radio.triggerSequence 整组入队, 见 engine.playS02Block);
//   · 阶段按时间 4 等分(每阶段 270s), **阶段内没有任何特殊触发** —— 主剧情播完就灌充数池,
//     全程"哔哔赖赖";
//   · 编队 ≤18 分钟跑完全程(engine 的 S02_SPEED_K 提速)。
//
// 数据结构(紧凑式, 由 scripts/apply-s02-script.mjs 展开成 radio.ts 的
// `{speaker, side, voiceSpeaker, text, en}` 条目):
//   [说话人, 中文, 英文]  —— 说话人查 CAST 得到 side/voiceSpeaker/代号。
//
// 角色代号(游戏里只显示代号; 用户给了"城 = 落锤", 其余按同一命名风格取):
//   关东·鹫护航中队  城=落锤  拓也=扳手  陈=算盘  凯=话匣  沈=咸鱼
//   关东·轰炸机编队  岩濑=烟斗  阿大=西瓜  小周=尺子  铁牛=铁牛  清水=药箱
//   关西·财阀安保队  结城=账房  明=三万  阿岛=年终  阿武=两成  由美=翼人
//   赛事直播          隼人=喇叭
//   其它(收尾碎语)    参谋=参谋  财务=账本  地勤=扳手兵  后勤=库管

/** 说话人 → [显示代号, side, voiceSpeaker(占位音色)] */
export const CAST: Record<string, [string, 'awacs' | 'ally' | 'enemy', string]> = {
  // —— 关东·鹫护航中队(玩家所在队) ——
  城: ['落锤', 'ally', 'ally1'],
  拓也: ['扳手', 'ally', 'ally2'],
  陈: ['算盘', 'ally', 'ally1'],
  凯: ['话匣', 'ally', 'ally2'],
  沈: ['咸鱼', 'ally', 'ally2'],
  // —— 关东·轰炸机 / 运输机编队 ——
  岩濑: ['烟斗', 'ally', 'ally1'],
  阿大: ['西瓜', 'ally', 'ally2'],
  小周: ['尺子', 'ally', 'ally2'],
  铁牛: ['铁牛', 'ally', 'ally1'],
  清水: ['药箱', 'ally', 'ally2'],
  // —— 关西·财阀安保航空队 ——
  结城: ['账房', 'enemy', 'enemy1'],
  明: ['三万', 'enemy', 'enemy2'],
  阿岛: ['年终', 'enemy', 'enemy1'],
  阿武: ['两成', 'enemy', 'enemy2'],
  由美: ['翼人', 'enemy', 'enemy1'],
  // —— 直播解说 + 收尾碎语里的路人 ——
  喇叭: ['喇叭', 'awacs', 'awacs'],
  参谋: ['参谋', 'ally', 'ally1'],
  财务: ['账本', 'enemy', 'enemy1'],
  地勤: ['扳手兵', 'ally', 'ally2'],
  后勤: ['库管', 'ally', 'ally2'],
  小兵: ['新兵', 'enemy', 'enemy2'],
};

export type Line = [speaker: string, zh: string, en: string];

// ---------------------------------------------------------------------------
// 阶段一(0–270s):炸锅!金库没了 —— 5 频道
// ---------------------------------------------------------------------------
export const S0: Line[] = [
  ['凯', '我去我去！底下炸出来的真是钱啊！满天飞的都是万元钞！我刚看见一沓子飘我机翼上了！',
    'Whoa whoa! That is money down there! Ten-thousand notes everywhere! One stack just flew past my wing!'],
  ['陈', '瞧你那点出息。这一炸，底下少说几十亿。咱们这趟双倍津贴，加起来还没人家零头多。',
    'Look at you. That blast just vaporised billions. Our double bonus is pocket change next to it.'],
  ['拓也', '几十亿？！咱们炸的不是军火库吗？',
    'Billions?! I thought we were bombing an arms depot?'],
  ['城', '军火库？军火库是给外面人听的。咱们真正的任务，就是炸人家钱库。',
    'Arms depot? That is what the paperwork says. Our actual job was their vault.'],
  ['沈', '管他炸什么呢。炸完赶紧回去，我还约了人下班喝酒。',
    'Whatever we hit. Let us wrap up — I have drinks booked after shift.'],
  ['阿大', '队长队长！真的是钱！我看见地下三层炸开，全是现金！还有金条！',
    'Lead, lead! It is really cash! The third basement is blown wide open — bills and gold bars!'],
  ['岩濑', '看见了就看见了，别嚷嚷。保密条例忘了？',
    'You saw it, fine. Keep it to yourself. Remember the secrecy clause?'],
  ['铁牛', '妈的！合着咱们冒着防空炮火飞过来，就是给人炸钱包的？',
    'Son of a — we flew through flak just so somebody could blow up a wallet?'],
  ['小周', '那、那咱们这算不算犯罪啊……',
    'S-so does that make us criminals...?'],
  ['清水', '算。但给钱多。你不干有的是人干。',
    'Yes. But it pays well. If you will not, someone else will.'],
  ['明', '我操我操我操！我的钱！我全部老婆本啊！三万啊！三万！',
    'No no no no! My money! Everything I saved for a wife! Thirty thousand!'],
  ['阿岛', '我的年终奖！我熬了一整年的年终奖啊！说没就没了？',
    'My year-end bonus! A whole year of overtime — gone just like that?'],
  ['阿武', '妈的，敢砸老子的盘。追上去！打下来一架抽两成，老子今天要回本！',
    'They smashed my stake. After them! Twenty percent a kill — I am breaking even today!'],
  ['由美', '我半年工资啊……我就想赚点化妆品钱……我保证金还在里面啊……',
    'Half a year of pay... I only wanted makeup money... my deposit was in there...'],
  ['结城', '都闭嘴。全体追击。击落一架轰炸机，补个人损失10%。击落队长机，补30%。',
    'Quiet. All units, pursue. Ten percent of personal losses per bomber down. Thirty for the lead.'],
  ['明', '收到！这波打完我就能娶媳妇了！',
    'Copy! After this run I can afford a wife!'],
  ['明', '关东的你们是不是有病！打仗就打仗，你炸人银行？！',
    'Are you Easterners sick?! Fight a war, fine — but you bombed a bank?!'],
  ['凯', '哟，这么急眼啊？你们开黑盘赚黑心钱的时候，怎么不说自己缺德啊？',
    'Oh, touchy. When you were running that book of yours, did you call yourselves crooks?'],
  ['阿岛', '那、那是我们应得的！你们这是抢劫！',
    'Th-that was ours by right! This is robbery!'],
  ['陈', '抢劫怎么了。我们老板给的多。',
    'And? Our boss pays well.'],
  ['由美', '你们卑鄙！你们无耻！',
    'You are despicable! Shameless!'],
  ['铁牛', '少废话！有本事追上来打！没本事就憋着！',
    'Shut it! Come up here and fight, or sit on it!'],
  ['阿武', '行，你们嘴硬。等下打下来，让你们跳伞都带着欠条。',
    'Fine, tough talk. When we drop you, you will bail out carrying an IOU.'],
  ['城', '行了，都别废话了。想打的过来，不想打的回去算账。',
    'Enough chatter. Come fight if you want, or go home and count your losses.'],
  ['结城', '好。咱们慢慢算。',
    'Good. We will settle it slowly.'],
  ['喇叭', '家人们！名场面啊！公频骂起来了！史上第一次因为炸金库引发的空战！',
    'Folks! A legendary moment! Open channel is on fire — the first air war started by a blown vault!'],
  ['喇叭', '最新赔率更新！关西追击成功1赔5，编队全身而退1赔2.5！',
    'Odds update! West pursuit succeeds: five to one. Formation escapes intact: two and a half.'],
  ['喇叭', '我刚才看见有人押了十万关东输，现在已经在天台了啊！',
    'Someone just put a hundred grand on the East losing. He is on the rooftop already!'],
  ['喇叭', '本场赛事由磐户军工独家赞助——磐户机载机炮，打钱准，打人更准！',
    'Tonight sponsored by Iwado Arms — Iwado gun pods: accurate on coin, deadlier on target!'],
];

// ---------------------------------------------------------------------------
// 阶段二(270–540s):追击!为了年终奖玩命
// ---------------------------------------------------------------------------
export const S1: Line[] = [
  ['凯', '我靠我靠！后面那个咬我尾了！老陈救我！',
    'Whoa whoa! One is on my tail! Old Chen, help me out!'],
  ['陈', '救你可以啊。这趟津贴分我一半。',
    'Sure I will. Half your bonus for this sortie.'],
  ['凯', '你抢劫啊！',
    'That is robbery!'],
  ['拓也', '别说了别说了！我这边也来一个！这小子疯了一样冲我！',
    'Not now! I have one too — the kid is charging me like a madman!'],
  ['沈', '哎，别往我这边引啊。我只想安安静静混完这趟。',
    'Hey, do not drag them my way. I just want a quiet shift.'],
  ['城', '都别闹！二对一缠住他们，别让他们靠近轰炸机。',
    'Knock it off! Two on one, tie them up — keep them off the bombers.'],
  ['陈', '真是的，拿双倍工资，干三倍的活。',
    'Double pay, triple work. Typical.'],
  ['铁牛', '来啊！过来啊！看老子不把你驾驶舱打烂！',
    'Come on! Get over here! I will shred your cockpit!'],
  ['阿大', '铁牛牛逼！哎哎左边！左边有一架绕过来了！',
    'Attaboy! Hey — left, left! One is swinging around!'],
  ['小周', '队长，三号引擎中弹了！速度掉了十节！',
    'Lead, engine three is hit! We lost ten knots!'],
  ['岩濑', '稳住。护航队会挡住的。',
    'Steady. The escorts will hold them.'],
  ['清水', '我们这边没事。伤员都稳着呢。你们前面加油。',
    'We are fine back here. Wounded are stable. Good hunting up front.'],
  ['铁牛', '妈的这小子滑得像条鱼！',
    'This one slips like a fish!'],
  ['阿大', '哎你们听公频，关西那边又吵起来了！',
    'Hey, listen to the open channel — the West is arguing again!'],
  ['明', '别跑！你给我站住！我的钱！',
    'Do not run! Hold still! My money!'],
  ['阿武', '你他妈喊什么喊！他能站住等你打？',
    'Stop yelling! You think he will wait for you?'],
  ['阿岛', '不行了不行了，我这老飞机追不上了……我的年终奖啊……',
    'I cannot keep up... this old crate is done... my bonus...'],
  ['由美', '我、我第一次打真仗……我手心全是汗……',
    'Th-this is my first real fight... my hands are soaked...'],
  ['结城', '都集中精神！打下来什么都有！打不下来，你们今年全白干！',
    'Focus! Bring them down and you get everything. Miss, and you worked this year for nothing!'],
  ['明', '我知道我知道！这波必须回本！',
    'I know, I know! This run has to break even!'],
  ['明', '你们关东的是不是男人！有本事停下来单挑！',
    'Are you Easterners even men?! Stop and fight me one on one!'],
  ['凯', '有本事你追上来啊。追不上就别嚷嚷。',
    'Catch up first. Then talk.'],
  ['阿岛', '你们耍赖！你们飞机比我们好！',
    'You cheat! Your planes are better!'],
  ['陈', '废话。我们老板给钱多，飞机当然好。',
    'Obviously. Our boss pays more, so our planes are better.'],
  ['由美', '你们太欺负人了……',
    'You are all so unfair...'],
  ['铁牛', '欺负你怎么了？谁让你们穷！',
    'Unfair? So what. Should have been born richer!'],
  ['阿武', '行，你们狂。等下你们中弹了，别喊救命。',
    'Enjoy the bravado. When you are hit, do not scream for help.'],
  ['拓也', '哎，你们到底亏了多少钱啊，这么拼命？',
    'Hey — how much did you actually lose, to fight this hard?'],
  ['明', '我三万！', 'Thirty thousand!'],
  ['阿岛', '我八万！', 'Eighty thousand!'],
  ['由美', '我五万……', 'Fifty thousand...'],
  ['凯', '哈哈哈哈就这点钱？你们至于玩命吗？',
    'Hahaha, that little? And you are betting your lives?'],
  ['结城', '那是你们老板赚得多。我们这点钱，就是命。',
    'Your boss earns more. For us, that little is our life.'],
  ['喇叭', '太刺激了！一边追一边骂！这哪是空战啊，这是街头讨债啊！',
    'Incredible! Chasing and shouting — this is not an air battle, this is debt collection!'],
  ['喇叭', '目前编队损失一架战机！赔率小幅波动！现在押"损失三架以内"1赔1.8！',
    'One fighter lost so far! Odds shifting. "Three losses or fewer" now pays one point eight!'],
  ['喇叭', '关西加油啊！再打下来一架，赔率直接翻倍！',
    'Come on, West! One more kill and the payout doubles!'],
  ['喇叭', '感谢玄坛军工赞助本场赛事——玄坛航空炸弹，炸得精准，亏得痛快！',
    'Sponsored by Gendan Arms — Gendan aerial bombs: precise hits, painful losses!'],
];

// ---------------------------------------------------------------------------
// 阶段三(540–810s):断后!打工人的牺牲
// ---------------------------------------------------------------------------
export const S2: Line[] = [
  ['城', '老陈、阿凯，带轰炸机先走！我和拓也、沈哥断后！',
    'Chen, Kai — take the bombers out. Takuya, Shen and I hold the rear.'],
  ['陈', '队长……这断后，额外算钱不？',
    'Lead... this rearguard — is that extra pay?'],
  ['城', '算！三倍补贴！殉职了抚恤金翻倍！',
    'Yes! Triple allowance. Double death benefit if it goes bad.'],
  ['陈', '收到！队长保重！',
    'Copy! Take care, lead!'],
  ['凯', '不是吧真断后啊？我还没娶媳妇呢！',
    'You are serious about the rearguard? I am not even married yet!'],
  ['沈', '得了，躲也躲不掉。打吧。',
    'No point dodging it. Let us fight.'],
  ['拓也', '队长……我还能活着回去领津贴不……',
    'Lead... am I getting home to collect the allowance...?'],
  ['城', '能。都撑住。撑到防空圈就赢了。',
    'You will. Hold the line. Reach the defence zone and we win.'],
  ['小周', '队长，又掉了一架护航机……',
    'Lead... another escort is gone...'],
  ['岩濑', '别看。加速。我们活着回去，他们才不算白死。',
    'Do not look. Throttle up. If we live, they did not die for nothing.'],
  ['铁牛', '……妈的。明明都是拿工资的，何必呢。',
    '...Damn. We are all just on payroll. What is the point.'],
  ['阿大', '刚才还跟我贫嘴呢……这就没了……',
    'He was joking with me a minute ago... and now he is gone...'],
  ['清水', '伤员都安静了。他们也在听。',
    'The wounded have gone quiet. They are listening too.'],
  ['明', '我打中一架！我打中了！哈哈哈哈回本了！我回本了！',
    'I got one! I hit him! Hahaha, I broke even! I broke even!'],
  ['明', '我操——！我刚回本啊——！',
    'Oh no —! I just broke even —!'],
  ['阿武', '明？明！……妈的，跟你们拼了！',
    'Ming? Ming! ...To hell with it — I am taking you all with me!'],
  ['阿岛', '完了完了……钱没赚到，命差点没了……',
    'That is it... no money, nearly no life...'],
  ['由美', '我不想打了……我想回家……我不要钱了……',
    'I do not want to fight... I want to go home... keep the money...'],
  ['结城', '……继续追。还差一点。',
    '...Keep pursuing. We are close.'],
  ['阿武', '知道了。', 'Understood.'],
  ['凯', '你们疯了！为了几万块钱玩命？',
    'You are insane! Throwing your lives away for a few thousand?!'],
  ['阿武', '几万块？那是老子全部家当！',
    'A few thousand? That is everything I own!'],
  ['拓也', '你们不会去打工吗……非要赌……',
    'Why not just get a job... instead of gambling...'],
  ['阿岛', '打工？打工一年赚多少？赌一把，顶三年。',
    'A job? A year of work pays what? One bet covers three years.'],
  ['沈', '哎，中弹了。', 'Ah. I am hit.'],
  ['沈', '各位，别赌了。真的会死人的。',
    'Everyone — stop gambling. People really do die.'],
  ['城', '沈哥……', 'Shen...'],
  ['结城', '你们现在退走，还来得及。',
    'Withdraw now and it is not too late.'],
  ['城', '退？退了回去没奖金。你当我们跟你们一样闲？',
    'Withdraw? No bonus if we do. You think we have your leisure?'],
  ['喇叭', '又掉一架！又掉一架！双方都杀红了眼了！',
    'Another one down! Another one! Both sides are seeing red!'],
  ['喇叭', '现在赔率已经冲到1赔12了！押关西翻盘的朋友，你们要发财了！',
    'Odds just hit twelve to one! If you backed the West, you are getting rich!'],
  ['喇叭', '致敬每一位在战场上拼搏的勇士！你们是真正的斗士！',
    'Salute to every warrior out there tonight! True fighters, all of you!'],
  ['喇叭', '本场赛事指定保险——平安寿险，战死赔双倍，赌输也有赔！',
    'Official insurer: Ping An Life — double payout for the fallen, and gamblers get covered too!'],
];

// ---------------------------------------------------------------------------
// 阶段四(810–1080s):收尾!赢了任务,亏了人生
// ---------------------------------------------------------------------------
export const S3: Line[] = [
  ['城', '任务完成。返航。点名。', 'Mission complete. Heading home. Roll call.'],
  ['陈', '老陈，在。', 'Old Chen, here.'],
  ['凯', '阿凯……在。沈哥和拓也……', 'Kai... here. Shen and Takuya...'],
  ['城', '知道了。回去给他们申请最高抚恤金。',
    'Understood. I will file for the maximum death benefit.'],
  ['陈', '三倍补贴……加上抚恤金……他们俩比咱们赚得多。',
    'Triple allowance plus death benefit... they are out-earning us.'],
  ['凯', '都什么时候了你还算这个！',
    'Is that what you are thinking about right now?!'],
  ['陈', '不算怎么办。人都没了，总得落点钱吧。',
    'What else? They are gone. Somebody should collect.'],
  ['岩濑', '各机报伤亡。', 'All aircraft, report casualties.'],
  ['小周', '机枪手铁牛……中弹牺牲了。', 'Gunner Panghu... killed in action.'],
  ['阿大', '刚才还骂我呢……这就没了。',
    'He was cursing me out a minute ago... and now he is gone.'],
  ['岩濑', '回去吧。跟后勤说，多给他家里发点抚恤金。',
    'Let us go home. Tell logistics to bump his family payout.'],
  ['清水', '我们这边伤员都没事。安全了。',
    'Our wounded are all right. We are safe.'],
  ['阿岛', '……就这么算了？', '...So we just let it go?'],
  ['由美', '不然呢……冲过去也是死。钱没了，再没了命，更亏。',
    'What else... pushing in means dying. Losing money is bad; losing money and your life is worse.'],
  ['阿武', '算了？不可能。下次，炸他们的盘口。连本带利赚回来。',
    'Let it go? Never. Next time we hit their book. Principal plus interest.'],
  ['结城', '回去报告老板。下个月，行动代号"讨债"。',
    'Report to the boss. Next month, operation name: Debt Collection.'],
  ['明', '……我钱还没要回来呢……', '...I still have not got my money back...'],
  ['阿武', '闭嘴吧你！人活着就不错了！',
    'Shut up! You are alive, that is enough!'],
  ['结城', '这次算你们赢。', 'This round is yours.'],
  ['城', '谈不上赢。各为其主罢了。',
    'Not a win. Just different employers.'],
  ['结城', '下次见面，就是我们讨债的时候。',
    'Next time we meet, we come to collect.'],
  ['城', '随时奉陪。只要你们老板给得起钱。',
    'Any time. As long as your boss can pay.'],
  ['阿岛', '你们等着！我们迟早炸回来！',
    'Just you wait! One day we bomb you back!'],
  ['陈', '行啊。先把你们自己的亏空填上再说吧。',
    'Sure. Fill your own hole first.'],
  ['喇叭', '胜利！编队成功撤回防空圈！破晓行动圆满结束！',
    'Victory! The formation is inside the defence zone! Operation Daybreak is a wrap!'],
  ['喇叭', '恭喜所有押中胜利的观众朋友们！今晚可以加餐了！',
    'Congratulations to everyone who backed the winners! Extra rations tonight!'],
  ['喇叭', '明天同一时间，洞川战线反攻战！关西能不能复仇翻盘，我们拭目以待！',
    'Same time tomorrow: the Dongchuan counter-offensive! Can the West avenge this? Stay tuned!'],
  ['喇叭', '感谢所有赞助商的大力支持！我们明天再见！',
    'Thanks to all our sponsors! See you tomorrow!'],
  // —— 收尾背景碎语(基地零星对话) ——
  ['参谋', '这次赚了多少？……三十亿？不错不错。抚恤金才几百万。',
    'How much did we clear? ...Three billion? Very nice. Death benefits were a few million.'],
  ['财务', '账全乱了……这得查到什么时候啊……',
    'The books are a disaster... how long is this audit going to take...'],
  ['地勤', '又大捷。哪次不是死一堆人，当官的升官发财。',
    'Another great victory. Same as always: bodies for the ground crew, promotions for the brass.'],
  ['小兵', '又要加班造炮弹……什么时候是个头啊。',
    'Overtime making shells again... when does it end.'],
  ['后勤', '三倍补贴……又要多掏一笔钱。唉。',
    'Triple allowance... another hole in the budget. Ugh.'],
  ['小兵', '老板亏几十亿都不心疼，老子亏几万就要玩命。',
    'The boss loses billions like it is nothing. I lose a few thousand and it costs my life.'],
];

// ---------------------------------------------------------------------------
// 充数池(纯碎嘴, 不推进剧情; 每阶段主剧情播完后循环灌)
// ---------------------------------------------------------------------------
/** 池 A:公频互怼(最百搭, 每阶段都能用) */
export const F_A: Line[] = [
  ['凯', '喂喂喂，关西的还在吗？别是跑了吧？',
    'Hey, West — still there? Or did you run?'],
  ['阿武', '跑？我们等着收你们的欠条呢。',
    'Run? We are waiting to collect your IOUs.'],
  ['陈', '你们那点保证金还够赔几架飞机啊？',
    'How many more airframes can your margin cover?'],
  ['阿岛', '关你屁事！反正比你们老板良心！',
    'None of your business! At least our boss has a conscience!'],
  ['铁牛', '良心？你们拿命去赌还谈良心？',
    'Conscience? You gamble with your lives and talk about conscience?'],
  ['由美', '至少我们是自己的钱……',
    'At least it is our own money...'],
  ['拓也', '自己的钱亏得最快，你们不懂？',
    'Your own money is the fastest to lose. Did nobody tell you?'],
  ['结城', '别跟他们废话。省点力气追。',
    'Stop wasting breath on them. Save it for the pursuit.'],
  ['城', '听见没，人家老板在省油钱。',
    'Hear that? Their boss is counting fuel.'],
  ['凯', '哎，你们谁开的是改装机？我们这边赌你三分钟内掉。',
    'Hey, who flies the hot-rod? We are taking bets you drop within three minutes.'],
  ['阿武', '开改装的怎么了？至少我的提成自己算。',
    'So what if it is modified? At least I count my own cut.'],
  ['沈', '都别吵了，吵得我头疼……',
    'Enough shouting. It is giving me a headache...'],
  ['凯', '哎，你们那边还剩几个能打的？报个数，我们好下注。',
    'Hey, how many of you can still fight? Call it out — we want a number to bet on.'],
  ['阿武', '报你个头。等下你们掉下来，我们自己数。',
    'Call it out? When you go down we will do the counting.'],
  ['小周', '那个……能不能先给我换顶头盔？这顶看着是别人用过的。',
    'Uh... could I get a different helmet first? This one clearly belonged to someone else.'],
  ['由美', '你们别打我们队长……他人其实挺好的……',
    'Please do not shoot our lead... he is actually a decent person...'],
];

/** 池 B:赛事直播(报赔率 / 插广告 / 拱火) */
export const F_B: Line[] = [
  ['喇叭', '赔率又动了！现在押"编队全员生还"1赔3.2，押"再掉两架"1赔2.1！',
    'Odds moved again! "Everyone survives" pays three point two, "two more losses" pays two point one!'],
  ['喇叭', '本场赛事特别鸣谢: 磐户军工、玄坛军工、平安寿险——战场上多一个朋友，就少一条命。',
    'Special thanks to Iwado Arms, Gendan Arms and Ping An Life — one more friend on the field, one less life lost.'],
  ['喇叭', '导播切一下关西的座舱——哎呀，这位朋友眼眶红了啊！',
    'Cut to a West cockpit — oh, look at those eyes, somebody is tearing up!'],
  ['喇叭', '观众朋友们，现在每分钟都有几十万上下，别走开，广告之后更精彩！',
    'Folks, fortunes are changing by the minute — stay with us, more after the break!'],
  ['喇叭', '有人问这算不算战争罪？我们把这个问题交给赞助商来回答。',
    'Someone asks if this counts as a war crime. We will let the sponsors answer that one.'],
  ['喇叭', '现在场上还剩多少架？导播说他也数不过来！',
    'How many are still flying? Our director says he lost count too!'],
  ['喇叭', '押注通道还有九十秒关闭！想翻本的朋友，抓紧！',
    'Betting closes in ninety seconds! If you want it back, move!'],
  ['喇叭', '这是一场没有输家的比赛——除了两边飞行员。',
    'A match with no losers tonight — except the pilots.'],
  ['喇叭', '导播说前面那架已经在冒烟了！观众朋友们，屏住呼吸！',
    'Our director says that one up front is already smoking! Hold your breath, folks!'],
  ['喇叭', '有观众问奖金怎么领？请到后台窗口，凭击落编号办理。',
    'A viewer asks how to claim his winnings? Back office window, bring your kill number.'],
];

/** 池 C:随机击落通讯(带电流杂音, 谁掉都播) */
export const F_C: Line[] = [
  ['明', '我的提成——！', 'My commission —!'],
  ['拓也', '早知道……就不贪这加班费了……',
    'If I had known... I would have skipped the overtime pay...'],
  ['阿岛', '我的房贷……还没还清啊……',
    'My mortgage... still not paid off...'],
  ['凯', '这下……不用交税了。', 'Well... no more taxes at least.'],
  ['阿武', '老板亏几十亿都没事，老子亏几万就要死……',
    'The boss loses billions and shrugs. I lose a few thousand and die...'],
  ['铁牛', '也好……再也不用上班了。', 'Fine... no more work shifts.'],
  ['城', '……收到。你的位置，我记下了。',
    '...Copy. I have your position noted.'],
];

/** 池 D:收尾/基地碎语(偏"任务已结束"的味道, 后两阶段用) */
export const F_D: Line[] = [
  ['参谋', '这个月的战果报表我看了，死的人比赚的零头还便宜。',
    'I read the monthly report. The dead cost less than the rounding error.'],
  ['财务', '又得做两套账……一套给上面，一套给我们自己看。',
    'Two sets of books again... one for the brass, one for us.'],
  ['地勤', '飞机回来一架修一架，人也一样。',
    'Planes come back one at a time and get patched. So do people.'],
  ['后勤', '补贴一发，这个季度的库房钱就没了。',
    'One allowance run and the quarterly warehouse budget is gone.'],
  ['小兵', '新闻里说我们是英雄。英雄怎么还不给加班费。',
    'The news calls us heroes. Heroes still do not get overtime.'],
  ['参谋', '下一场报价已经出来了。比这场高两成。',
    'Next contract is already quoted. Twenty percent higher than this one.'],
  ['地勤', '这批弹壳回收还能卖钱，别当垃圾倒了。',
    'These spent casings still fetch scrap money. Do not bin them.'],
];

/** 每个阶段的充数池轮换顺序(引擎按 stage % 取; 见 engine.S02_FILLER) */
export const FILLER_POOLS: Line[][] = [F_A, F_B, F_C, F_D];

/** 阶段主剧情(4 阶段, 每阶段 5 频道顺序: 鹫 / 轰炸机 / 关西 / 公频 / 直播) */
export const STAGE_MAIN: Line[][] = [S0, S1, S2, S3];
